/*******************************************************************************
 * Copyright (c) 2000, 2019 IBM Corporation and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.jdt.internal.compiler.parser;

/*An interface that contains static declarations for some basic information
 about the parser such as the number of rules in the grammar, the starting state, etc...*/
public interface ParserBasicInformation {

	public final static int
    // BEGIN_AUTOGENERATED_REGION

					ERROR_SYMBOL = 134,
					MAX_NAME_LENGTH = 41,
					NUM_STATES = 1171,

					NT_OFFSET = 134,
					SCOPE_UBOUND = 299,
					SCOPE_SIZE = 300,
					LA_STATE_OFFSET = 16798,
					MAX_LA = 1,
					NUM_RULES = 874,
					NUM_TERMINALS = 134,
					NUM_NON_TERMINALS = 399,
					NUM_SYMBOLS = 533,
					START_STATE = 1599,
					EOFT_SYMBOL = 63,
					EOLT_SYMBOL = 63,
					ACCEPT_ACTION = 16797,
					ERROR_ACTION = 16798;
}
