/*******************************************************************************
 * Copyright (c) 2000, 2021 IBM Corporation and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.jdt.internal.compiler.parser;

/*An interface that contains static declarations for some basic information
 about the parser such as the number of rules in the grammar, the starting state, etc...*/
public interface ParserBasicInformation {

	public final static int
	// BEGIN_AUTOGENERATED_REGION

					ERROR_SYMBOL = 140,
					MAX_NAME_LENGTH = 53,
					NUM_STATES = 1228,

					NT_OFFSET = 140,
					SCOPE_UBOUND = 320,
					SCOPE_SIZE = 321,
					LA_STATE_OFFSET = 18501,
					MAX_LA = 1,
					NUM_RULES = 942,
					NUM_TERMINALS = 140,
					NUM_NON_TERMINALS = 434,
					NUM_SYMBOLS = 574,
					START_STATE = 1152,
					EOFT_SYMBOL = 66,
					EOLT_SYMBOL = 66,
					ACCEPT_ACTION = 18500,
					ERROR_ACTION = 18501;
}
