/*******************************************************************************
 * Copyright (c) 2000, 2019 IBM Corporation and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.jdt.internal.compiler.parser;

/**
 * IMPORTANT NOTE: These constants are dedicated to the internal Scanner implementation.
 * It is mirrored in org.eclipse.jdt.core.compiler public package where it is API.
 * The mirror implementation is using the backward compatible ITerminalSymbols constant
 * definitions (stable with 2.0), whereas the internal implementation uses TerminalTokens
 * which constant values reflect the latest parser generation state.
 */
/**
 * Maps each terminal symbol in the java-grammar into a unique integer.
 * This integer is used to represent the terminal when computing a parsing action.
 *
 * Disclaimer : These constant values are generated automatically using a Java
 * grammar, therefore their actual values are subject to change if new keywords
 * were added to the language (for instance, 'assert' is a keyword in 1.4).
 */
public interface TerminalTokens {

	// special tokens not part of grammar - not autogenerated
	int TokenNameNotAToken = 0,
							TokenNameWHITESPACE = 1000,
							TokenNameCOMMENT_LINE = 1001,
							TokenNameCOMMENT_BLOCK = 1002,
							TokenNameCOMMENT_JAVADOC = 1003;

	// BEGIN_AUTOGENERATED_REGION
	int TokenNameIdentifier = 22,
							TokenNameabstract = 54,
							TokenNameassert = 82,
							TokenNameboolean = 105,
							TokenNamebreak = 83,
							TokenNamebyte = 106,
							TokenNamecase = 107,
							TokenNamecatch = 108,
							TokenNamechar = 109,
							TokenNameclass = 70,
							TokenNamecontinue = 84,
							TokenNameconst = 133,
							TokenNamedefault = 78,
							TokenNamedo = 85,
							TokenNamedouble = 110,
							TokenNameelse = 119,
							TokenNameenum = 76,
							TokenNameextends = 92,
							TokenNamefalse = 37,
							TokenNamefinal = 55,
							TokenNamefinally = 117,
							TokenNamefloat = 111,
							TokenNamefor = 86,
							TokenNamegoto = 134,
							TokenNameif = 87,
							TokenNameimplements = 129,
							TokenNameimport = 112,
							TokenNameinstanceof = 17,
							TokenNameint = 113,
							TokenNameinterface = 75,
							TokenNamelong = 114,
							TokenNamenative = 56,
							TokenNamenew = 36,
							TokenNamenull = 38,
							TokenNamepackage = 91,
							TokenNameprivate = 57,
							TokenNameprotected = 58,
							TokenNamepublic = 59,
							TokenNamereturn = 88,
							TokenNameshort = 115,
							TokenNamestatic = 50,
							TokenNamestrictfp = 60,
							TokenNamesuper = 34,
							TokenNameswitch = 52,
							TokenNamesynchronized = 53,
							TokenNamethis = 35,
							TokenNamethrow = 79,
							TokenNamethrows = 127,
							TokenNametransient = 61,
							TokenNametrue = 39,
							TokenNametry = 89,
							TokenNamevoid = 116,
							TokenNamevolatile = 62,
							TokenNamewhile = 80,
							TokenNamemodule = 120,
							TokenNameopen = 121,
							TokenNamerequires = 122,
							TokenNametransitive = 128,
							TokenNameexports = 123,
							TokenNameopens = 124,
							TokenNameto = 130,
							TokenNameuses = 125,
							TokenNameprovides = 126,
							TokenNamewith = 131,
							TokenNameIntegerLiteral = 40,
							TokenNameLongLiteral = 41,
							TokenNameFloatingPointLiteral = 42,
							TokenNameDoubleLiteral = 43,
							TokenNameCharacterLiteral = 44,
							TokenNameStringLiteral = 45,
							TokenNameTextBlock = 46,
							TokenNamePLUS_PLUS = 2,
							TokenNameMINUS_MINUS = 3,
							TokenNameEQUAL_EQUAL = 19,
							TokenNameLESS_EQUAL = 12,
							TokenNameGREATER_EQUAL = 13,
							TokenNameNOT_EQUAL = 20,
							TokenNameLEFT_SHIFT = 18,
							TokenNameRIGHT_SHIFT = 14,
							TokenNameUNSIGNED_RIGHT_SHIFT = 16,
							TokenNamePLUS_EQUAL = 93,
							TokenNameMINUS_EQUAL = 94,
							TokenNameMULTIPLY_EQUAL = 95,
							TokenNameDIVIDE_EQUAL = 96,
							TokenNameAND_EQUAL = 97,
							TokenNameOR_EQUAL = 98,
							TokenNameXOR_EQUAL = 99,
							TokenNameREMAINDER_EQUAL = 100,
							TokenNameLEFT_SHIFT_EQUAL = 101,
							TokenNameRIGHT_SHIFT_EQUAL = 102,
							TokenNameUNSIGNED_RIGHT_SHIFT_EQUAL = 103,
							TokenNameOR_OR = 31,
							TokenNameAND_AND = 30,
							TokenNamePLUS = 4,
							TokenNameMINUS = 5,
							TokenNameNOT = 66,
							TokenNameREMAINDER = 9,
							TokenNameXOR = 24,
							TokenNameAND = 21,
							TokenNameMULTIPLY = 8,
							TokenNameOR = 28,
							TokenNameTWIDDLE = 67,
							TokenNameDIVIDE = 10,
							TokenNameGREATER = 15,
							TokenNameLESS = 11,
							TokenNameLPAREN = 23,
							TokenNameRPAREN = 25,
							TokenNameLBRACE = 51,
							TokenNameRBRACE = 33,
							TokenNameLBRACKET = 6,
							TokenNameRBRACKET = 69,
							TokenNameSEMICOLON = 26,
							TokenNameQUESTION = 29,
							TokenNameCOLON = 65,
							TokenNameCOMMA = 32,
							TokenNameDOT = 1,
							TokenNameEQUAL = 77,
							TokenNameAT = 47,
							TokenNameELLIPSIS = 118,
							TokenNameARROW = 104,
							TokenNameCOLON_COLON = 7,
							TokenNameBeginLambda = 48,
							TokenNameBeginIntersectionCast = 68,
							TokenNameBeginTypeArguments = 90,
							TokenNameElidedSemicolonAndRightBrace = 73,
							TokenNameAT308 = 27,
							TokenNameAT308DOTDOTDOT = 132,
							TokenNameBeginCaseExpr = 74,
							TokenNameRestrictedIdentifierYield = 81,
							TokenNameJAVADOC_FORMAL_PART_START = 63,
							TokenNameJAVADOC_FORMAL_PART_SEPARATOR = 71,
							TokenNameJAVADOC_FORMAL_PART_END = 72,
							TokenNameold = 49,
							TokenNameEOF = 64,
							TokenNameERROR = 135;
}
