/*******************************************************************************
 * Copyright (c) 2000, 2019 IBM Corporation and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.jdt.internal.compiler.parser;

/**
 * IMPORTANT NOTE: These constants are dedicated to the internal Scanner implementation.
 * It is mirrored in org.eclipse.jdt.core.compiler public package where it is API.
 * The mirror implementation is using the backward compatible ITerminalSymbols constant
 * definitions (stable with 2.0), whereas the internal implementation uses TerminalTokens
 * which constant values reflect the latest parser generation state.
 */
/**
 * Maps each terminal symbol in the java-grammar into a unique integer.
 * This integer is used to represent the terminal when computing a parsing action.
 *
 * Disclaimer : These constant values are generated automatically using a Java
 * grammar, therefore their actual values are subject to change if new keywords
 * were added to the language (for instance, 'assert' is a keyword in 1.4).
 */
public interface TerminalTokens {

	// special tokens not part of grammar - not autogenerated
	int TokenNameNotAToken = 0,
							TokenNameWHITESPACE = 1000,
							TokenNameCOMMENT_LINE = 1001,
							TokenNameCOMMENT_BLOCK = 1002,
							TokenNameCOMMENT_JAVADOC = 1003;

	// BEGIN_AUTOGENERATED_REGION
	int TokenNameIdentifier = 21,
							TokenNameabstract = 53,
							TokenNameassert = 83,
							TokenNameboolean = 107,
							TokenNamebreak = 84,
							TokenNamebyte = 108,
							TokenNamecase = 93,
							TokenNamecatch = 109,
							TokenNamechar = 110,
							TokenNameclass = 70,
							TokenNamecontinue = 85,
							TokenNameconst = 134,
							TokenNamedefault = 78,
							TokenNamedo = 86,
							TokenNamedouble = 111,
							TokenNameelse = 121,
							TokenNameenum = 76,
							TokenNameextends = 94,
							TokenNamefalse = 41,
							TokenNamefinal = 54,
							TokenNamefinally = 118,
							TokenNamefloat = 112,
							TokenNamefor = 87,
							TokenNamegoto = 135,
							TokenNameif = 88,
							TokenNameimplements = 131,
							TokenNameimport = 113,
							TokenNameinstanceof = 17,
							TokenNameint = 114,
							TokenNameinterface = 75,
							TokenNamelong = 115,
							TokenNamenative = 55,
							TokenNamenew = 36,
							TokenNamenull = 42,
							TokenNamepackage = 92,
							TokenNameprivate = 56,
							TokenNameprotected = 57,
							TokenNamepublic = 58,
							TokenNamereturn = 89,
							TokenNameshort = 116,
							TokenNamestatic = 39,
							TokenNamestrictfp = 59,
							TokenNamesuper = 34,
							TokenNameswitch = 63,
							TokenNamesynchronized = 40,
							TokenNamethis = 35,
							TokenNamethrow = 80,
							TokenNamethrows = 119,
							TokenNametransient = 60,
							TokenNametrue = 43,
							TokenNametry = 90,
							TokenNamevoid = 117,
							TokenNamevolatile = 61,
							TokenNamewhile = 81,
							TokenNamemodule = 122,
							TokenNameopen = 123,
							TokenNamerequires = 124,
							TokenNametransitive = 129,
							TokenNameexports = 125,
							TokenNameopens = 126,
							TokenNameto = 132,
							TokenNameuses = 127,
							TokenNameprovides = 128,
							TokenNamewith = 133,
							TokenNameIntegerLiteral = 44,
							TokenNameLongLiteral = 45,
							TokenNameFloatingPointLiteral = 46,
							TokenNameDoubleLiteral = 47,
							TokenNameCharacterLiteral = 48,
							TokenNameStringLiteral = 49,
							TokenNameTextBlock = 50,
							TokenNamePLUS_PLUS = 2,
							TokenNameMINUS_MINUS = 3,
							TokenNameEQUAL_EQUAL = 19,
							TokenNameLESS_EQUAL = 12,
							TokenNameGREATER_EQUAL = 13,
							TokenNameNOT_EQUAL = 20,
							TokenNameLEFT_SHIFT = 18,
							TokenNameRIGHT_SHIFT = 14,
							TokenNameUNSIGNED_RIGHT_SHIFT = 16,
							TokenNamePLUS_EQUAL = 95,
							TokenNameMINUS_EQUAL = 96,
							TokenNameMULTIPLY_EQUAL = 97,
							TokenNameDIVIDE_EQUAL = 98,
							TokenNameAND_EQUAL = 99,
							TokenNameOR_EQUAL = 100,
							TokenNameXOR_EQUAL = 101,
							TokenNameREMAINDER_EQUAL = 102,
							TokenNameLEFT_SHIFT_EQUAL = 103,
							TokenNameRIGHT_SHIFT_EQUAL = 104,
							TokenNameUNSIGNED_RIGHT_SHIFT_EQUAL = 105,
							TokenNameOR_OR = 31,
							TokenNameAND_AND = 30,
							TokenNamePLUS = 4,
							TokenNameMINUS = 5,
							TokenNameNOT = 66,
							TokenNameREMAINDER = 9,
							TokenNameXOR = 24,
							TokenNameAND = 22,
							TokenNameMULTIPLY = 8,
							TokenNameOR = 28,
							TokenNameTWIDDLE = 67,
							TokenNameDIVIDE = 10,
							TokenNameGREATER = 15,
							TokenNameLESS = 11,
							TokenNameLPAREN = 23,
							TokenNameRPAREN = 25,
							TokenNameLBRACE = 37,
							TokenNameRBRACE = 33,
							TokenNameLBRACKET = 6,
							TokenNameRBRACKET = 69,
							TokenNameSEMICOLON = 26,
							TokenNameQUESTION = 29,
							TokenNameCOLON = 65,
							TokenNameCOMMA = 32,
							TokenNameDOT = 1,
							TokenNameEQUAL = 79,
							TokenNameAT = 38,
							TokenNameELLIPSIS = 120,
							TokenNameARROW = 106,
							TokenNameCOLON_COLON = 7,
							TokenNameBeginLambda = 51,
							TokenNameBeginIntersectionCast = 68,
							TokenNameBeginTypeArguments = 91,
							TokenNameElidedSemicolonAndRightBrace = 71,
							TokenNameAT308 = 27,
							TokenNameAT308DOTDOTDOT = 130,
							TokenNameBeginCaseExpr = 72,
							TokenNameRestrictedIdentifierYield = 82,
							TokenNameRestrictedIdentifierrecord = 77,
							TokenNameJAVADOC_FORMAL_PART_START = 62,
							TokenNameJAVADOC_FORMAL_PART_SEPARATOR = 73,
							TokenNameJAVADOC_FORMAL_PART_END = 74,
							TokenNameold = 52,
							TokenNameEOF = 64,
							TokenNameERROR = 136;
}
