name: Test

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Check out fsc4j/eclipse.platform.releng.aggregator
      uses: actions/checkout@v3
      with:
        repository: fsc4j/eclipse.platform.releng.aggregator
    - uses: actions/checkout@v3
      with:
        path: eclipse.jdt.core
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Install toolchains.xml
      run: |
        mkdir -p $HOME/.m2
        cat $HOME/.m2/toolchains.xml
        cat << EOF > $HOME/.m2/toolchains.xml
        <toolchains>
          <toolchain>
            <type>jdk</type>                 
            <provides>
              <version>11</version>        
              <vendor>oracle</vendor>
              <id>JavaSE-11</id>           
            </provides>
            <configuration>
              <jdkHome>$JAVA_HOME_11_X64</jdkHome>
            </configuration>
          </toolchain>
        </toolchains>
        EOF
    - name: Build eclipse.platform.releng.prereqs.sdk
      run: |
        cd eclipse.platform.releng.prereqs.sdk
        mvn install
    - name: Build eclipse.jdt.core
      run: |
        cd eclipse.jdt.core/org.eclipse.jdt.core
        mvn compile
    - name: Download JUnit
      run: |
        cd eclipse.jdt.core/org.eclipse.jdt.core
        mvn dependency:copy -Dartifact=org.junit.platform:junit-platform-console-standalone:1.9.3
    - name: Build and run FSC4J test suite
      run: |
        set -e
        cd eclipse.jdt.core/org.eclipse.jdt.core
        export JUNIT_PATH=`pwd`/target/dependency/junit-platform-console-standalone-1.9.3.jar
        java -cp target/classes org.eclipse.jdt.internal.compiler.batch.Main -11 -proc:none -d target/classes s4jie2-tests/runner
        java -cp target/classes org.eclipse.jdt.core.s4jie2TestSuite
